### ISSUE TITLE
When using a custom Dafny.dll and language server reset is hard

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#105]
If I experiment with a custom version of Dafny,
reseting the IDE back takes reseting the config values to default
AND uninstall/reinstall.

I would be nice if I could just reset it in the config

**Comment by camrein** [comment]
Sorry but I have a hard time following your description.
Do you mean that by default you're using the automatically installed Dafny version? And once you switch to a custom installation and back to the automatic installation you need to re-install the extension to re-trigger the automatic installation?

If I'm right, I suppose you're changing the paths to `Dafny.dll` and `DafnyLanguageServer.dll` through VSCodes UI:
![image](https://user-images.githubusercontent.com/18049310/146779588-45e45d0c-8bd9-44c9-a68d-8734e0b15bb2.png)

I guess if you remove the manual entry in these two fields it's neither `null` nor `undefined` but an empty string from the extension's perspective. 
You could probably click on the gear to the left and hit `Reset setting` to correctly reset it:
![image](https://user-images.githubusercontent.com/18049310/146779800-ebbc7a37-8b64-4291-a355-901e4ce331ac.png)

Alternatively, you could remove the entry from the underlying `settings.json` of your VSCode extension.
Restarting VSCode will still be necessary, but it should save you from re-installing the extension.

**Comment by seebees** [comment]
Yes, you have described what I do.
With the addition, that even when I reset the setting,
sometimes I have to uninstall/reinstall to get the plugin to download Dafny again...

**Comment by camrein** [comment]
I've quickly tested what you're describing. The problem is, that when you "clear" the text field by removing its contents, VSCode treats the value as an empty string instead of an unconfigured setting (you can see that by checking `settings.json`).
As I suggested, clicking the gear next to the setting and selecting *Reset Setting* correctly removes the configuration entry.

You can also double-check this behavior by opening the tab *Output* and select *Dafny VSCode*.
For example, with the automatic installation:
![image](https://user-images.githubusercontent.com/18049310/147245306-41222fd4-6bcb-43f3-801c-0c8a5c5f6024.png)

Removing the contents of the setting by deleting the content instead of resetting it:
![image](https://user-images.githubusercontent.com/18049310/147245479-aeb73920-2727-42a2-9882-1b821d9d0d49.png)

I guess it makes sense to treat the empty string the same as if it was unconfigured.
