### ISSUE TITLE
Possibly-overspecific supported runtimes pattern?

### ISSUE THREAD

**Issue by dijkstracula** [dafny-lang/ide-vscode#110]
Dear Dafny team,

Apologies in advance if this is not in fact an issue but simply the state of the world.

I've been working on getting Dafny running on an M1 (arm64) Mac.  I've been following the [Dafny INSTALL wiki](https://github.com/dafny-lang/dafny/wiki/INSTALL) except that I've dropped in a custom-compiled Z3 4.8.5 since there does not appear to be an uploaded non-Intel release.  Luckily, the Dafny executable does appear to work on my machine (insofar as my trivial "hello world" program verifies, as does running `./Scripts/quicktest.sh`.

Now that the language itself appears to be running on this hardware, I'd next like to use the VSCode plugin with the language server - however, since no arm64 binaries for ASP .NET Core 5.0 have been released, I'm stuck using 6.0.  The Wiki does mention that Dafny itself runs under 6.0 (indeed, the wording suggests it's required); however, the [supported runtimes regex](https://github.com/dafny-lang/ide-vscode/blob/f087194118091e710f5f83882e0d4c4ed81cf6ef/src/constants.ts#L40) explicitly only matches against 5.0, so VSCode pops up a "There is no compatible dotnet runtime installed" dialog.

I'm not familiar with the .NET ecosystem, but I wonder whether this could safely be extended to support 5.0 as well as later versions?  Thanks!

**Comment by camrein** [comment]
Thanks a lot for your suggestion.
As far as I remember, .NET (Core) does not guarantee backward compatibility. Unfortunately, I've only found [this](https://github.com/dotnet/runtime/issues/1959#issuecomment-576937893) GitHub issue confirming my statement.

I see that this check might be a bit too restrictive. Dafny 3.3 targets .NET Core 5.0, making sense for this compatibility check. However, it's hindering the next iteration, which targets 6.0, besides the issue you've already mentioned.

So there are a few things we have to keep in mind:

- The VSCode intends to support various Dafny versions in the future. Therefore, fixing the release to a specific .NET Version becomes problematic. For this case, we'd have to create a compatibility matrix.
- I've seen many people compile Dafny from source but not the VSCode extension. So the VSCode extension may not be aware of an upcoming Dafny release that may target another dotnet version.

Therefore, I propose that we either allow disabling the compatibility check or let people configure the targeted dotnet version themselves.
Another thing I had in mind in a very early build is to support Dafny installations behind docker and/or wsl. This worked flawlessly as long as you didn't create multi-file projects (you'd have to mount the workspace dir in the docker container). However, this is currently not possible because of the compatibility check hence why I believe the ability to disable the check for dotnet installations might be generally helpful.

**Comment by dijkstracula** [comment]
>  I propose that we either allow disabling the compatibility check or let people configure the targeted dotnet version themselves.

I think either of these would address my issue, thank you.

> However, it's hindering the next iteration, which targets 6.0

Sorry, just for clarity: by the next iteration, do you mean the next minor or major Dafny version, or a different thing?

**Comment by camrein** [comment]
> > However, it's hindering the next iteration, which targets 6.0
> 
> Sorry, just for clarity: by the next iteration, do you mean the next minor or major Dafny version, or a different thing?

No worries. I meant that Dafny 3.4 will be built against .NET 6.0.

**Comment by dijkstracula** [comment]
Got it, thanks for the clarification.

**Comment by camrein** [comment]
Resolved by #111
