### ISSUE TITLE
IDE plugin resolution time keeps increasing over time.

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/ide-vscode#117]
I observed that, in large projects, the parsing + resolution time takes more and more time, and it goes back to very fast when Visual Studio Code is restarted. It might be related to the other issue of the underlying process dotnet.exe increasing in RAM (4Gb when it's at the slowest point, before restarting manually the vs code extension).

Note that it's possible trigger the same problem by simply enabling "verify on change" on big projects, and modify the file a lot.

Not sure where to start though to debug this issue.

**Comment by camrein** [comment]
> It might be related to the other issue of the underlying process dotnet.exe increasing in RAM (4Gb when it's at the slowest point, before restarting manually the vs code extension).

There must be some memory leak. You could diagnose this by attaching a profiler to the dotnet process of the language server.

> Note that it's possible trigger the same problem by simply enabling "verify on change" on big projects, and modify the file a lot.

It may not necessarily need a big project. I'm thinking about creating a test case that repeatedly opens and closes (and maybe changes) a Dafny document. That might make it easier to profile and identify the memory leak. As you suggested, I believe too that the root cause is probably the memory leak that might have a negative impact on the garbage collector or some data store that is performing poorly.

**Comment by seebees** [comment]
Complete shot in the dark, it _may_ be related to comments.
I was working on something last night.
I had commented out a _lot_ of code to do the work.
As I was working the resolver was very slow.

When I deleted the commented code because I was done with it,
it appeared that the resolver sped up...

One data point :)

**Comment by cpitclaudel** [comment]
Wasn't this related related to ghost overlays?

**Comment by MikaelMayer** [comment]
I think the error went away
