### ISSUE TITLE
There is no compatible dotnet runtime installed

### ISSUE THREAD

**Issue by ByteDrummer** [dafny-lang/ide-vscode#138]
I'm on Manjaro Linux, and I keep getting the following error on VSCode when opening a .dfy file: 
> There is no compatible dotnet runtime installed. Dafny requires the ASP.NET Core Runtime 5.0 or 6.0

This doesn't make sense given the following:
```
dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

I've tried setting `dafny.dotnetExecutablePath` to `/usr/bin/dotnet` which doesn't help.

**Comment by camrein** [comment]
This might be related to #112: At this time, the extension doesn't distinguish between the actual error, i.e., dotnet not found, not executable, wrong version, etc.
Since your installation looks fine and [this regex](https://github.com/dafny-lang/ide-vscode/blob/a9eb397786dc6240d1bbc54e2fc3d8a51ca5c65e/src/constants.ts#L43) matches with one of your listed runtimes, I believe it must be related to something like this. Since I don't think that you've accidentally added any whitespace to the configuration, I suppose that VSCode cannot execute the specified dotnet executable, maybe a permission problem.
It's hard to diagnose the actual problem; thus, we have to make sure to improve error reporting when no suitable dotnet installation was found.

**Comment by ByteDrummer** [comment]
It looks like it was a permission problem. I was using the Flatpak version of VSCode, so I removed it and instead installed `visual-studio-code-bin` from the AUR. This version works fine, so I guess Flatpaks have limited access to the host environment.

**Comment by camrein** [comment]
Thanks so much for testing this out and reporting back.
That's a +1 that we should better inform about the dotnet installation problems we encounter.

**Comment by MikaelMayer** [comment]
The dotnet messages have been improved now, and this issue has been fixed. Closing as fixed.

**Comment by seebees** [comment]
@MikaelMayer Your comment says "closing" but it looks open?
