### ISSUE TITLE
erroneous plugin version number?

### ISSUE THREAD

**Issue by franck44** [dafny-lang/ide-vscode#17]
Thanks for updating the plugin to support Dafny3.
The version number seems to be 1.3.0 but in the status bar, there is Dafny Language Server 2.3.0 that is displayed.

Questions:
1. is it a mismatch?
2. the _ Dafny Language Server 2.3.0_ is rather long and takes a wide space in the status bar. Is there a way to shorten it?

**Comment by camrein** [comment]
There are currently three versions to distinguish. Based on the recent update, you'll most likely have these versions:

- VSCode extension: 1.3.0
- Dafny Compiler: 3.0.0.30107 (this is 3.0.0 PreRelease-2 packaged with the language server)
- Language Server: 2.3.0

Since these are three individual software components, I'd rather leave the versioning of them separated. However, the next update of the language server will move its version to 3.0.0 due to the newly required .NET version (but this is merely a coincidence that it's on par with the compiler version).

I agree; the text "Dafny Language Server Version: 2.3.0" is pretty long. I changed it to "DafnyLS: 2.3.0".

**Comment by RustanLeino** [comment]
For bug reporting and trying to diagnose problems, it would be great if these 3 components and their version numbers were readily available in one place. I don't know if that's easy to do. For example, it would be great if all three were listed on the help page or were available from a menu selection.

**Comment by camrein** [comment]
That makes sense to me and emphasizes my preference to keep these versions independent.
Unfortunately, it does not appear that dotnet CLI provides an argument to show the version of an assembly. It appears that including another executable to extract this information would be the only possibility; thus, I'd rather leave it as is.

**Comment by camrein** [comment]
I'm closing this issue as the next Dafny VSCode iteration will include a feature to list all three versions:
![image](https://user-images.githubusercontent.com/18049310/133433975-4dc89a61-fba1-4179-b79c-099fd686db4a.png)
