### ISSUE TITLE
`Success` and `Error` in the same message

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/ide-vscode#198]
The following hover is quite confusing:

```
predicate f(x: int) {
  x > 0
}

predicate T(x: int, y: bool) {
  f(x) && y
}

method M()
  ensures T(-2, true)
{
}
```

![image](https://user-images.githubusercontent.com/8181630/177882188-81d5f6f6-3b1c-4db1-a172-00056f19b1a0.png)

Also: why is the underline all broken up?

![image](https://user-images.githubusercontent.com/8181630/177882266-8dbe1b5b-0e82-4e65-96a5-b5aaac11c34c.png)

Also: maybe we should document the meaning of the sidebar icons in the README (or put a link in there to the relevant docs): that's where I went to try to understand them.

**Comment by MikaelMayer** [comment]
The highlighting not ending on a parenthesis will be fixed when https://github.com/dafny-lang/dafny/pull/2202 will be merged.

There is one error and one success simply because under the caret, there are two postconditions in one. Dafny splits postconditions.
Once https://github.com/dafny-lang/dafny/pull/2153 will be finished and merged, I'll look into explicating what exactly fails in the error message.

**Comment by MikaelMayer** [comment]
![image](https://user-images.githubusercontent.com/3601079/178058374-a1e5e9ca-2c5e-493a-bb60-d00310962741.png)
![image](https://user-images.githubusercontent.com/3601079/178058713-1266a23f-fdb4-4494-844a-488cc214c797.png)
![image](https://user-images.githubusercontent.com/3601079/178058908-71425938-57a4-454d-805d-2923d7c4de73.png)
![image](https://user-images.githubusercontent.com/3601079/178063330-dd346ddf-aa60-487e-a368-3a4af572aeac.png)
![image](https://user-images.githubusercontent.com/3601079/178063848-d0fb02d9-c743-4ffc-9e34-c5f8731c79d1.png)
![image](https://user-images.githubusercontent.com/3601079/178068281-f15fa83f-6180-4de1-ab63-b65957f6c86b.png)
![image](https://user-images.githubusercontent.com/3601079/178068650-24c14da1-d247-4027-b784-2eb055242e6b.png)
Here are a few images I'm putting in the documentation, so that they can be accessed easily from the HTML and PDF versions from this PR:
https://github.com/dafny-lang/dafny/pull/2385

**Comment by cpitclaudel** [comment]
It would be good to put `Success` and `Error` in the same bold font; I did not understand that there was two separate things in that message.

I also find "this postcondition holds" quite confusing when we also say "A postcondition might not hold" in the same spot.

And, we talk about a return path, but the error isn't on a return path, right?

I'm not sure what the best fix is for the last two.
