### ISSUE TITLE
Really slow on Mac

### ISSUE THREAD

**Issue by johnwickerson** [dafny-lang/ide-vscode#21]
I just upgraded today having not used Dafny in VSCode for a few weeks, and suddenly the performance has gone through the floor! It seems to take a minute or so just to register each keystroke, and it's making my laptop overheat!

I'm on Mac OS 10.15.7 and running the following VSCode version:

> Version: 1.53.2
> Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
> Date: 2021-02-11T11:45:54.515Z (1 wk ago)
> Electron: 11.2.1
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Darwin x64 19.6.0

Please let me know what information you would like -- I'm not quite sure how to report "performance issues" like this!

**Comment by camrein** [comment]
You may be negatively impacted by the automatic verification which is set to run with every change by default. I recommend you to set it to either "onsave" or to "never" and check if it improves your experience.

**Comment by johnwickerson** [comment]
Thanks! Yes I found that switch after posting my issue, and it has indeed helped a bit. I still feel that performance is way worse than it was before updating, but it's hard to put my finger on anything specific.

**Comment by camrein** [comment]
You could compare it to the old version if you'd like to make sure, it's still available on the store: https://marketplace.visualstudio.com/items?itemName=correctnessLab.dafny-vscode-legacy

Since the new version uses less indirection compared to the old, it's hard to guess what could make it slower - except that you deal with huge documents. My first guess would be that Dafny's feature set grew in v3.0.0 compared to v2.3.0. But you would notice this when comparing the compile times of both versions.

**Comment by fpoli** [comment]
I'm using Mac and I also find that the extension is some orders of magnitude slower than running dafny from the command line. In some cases the extension triggers a verification request when I *click* in the document to move the cursor.

**Comment by fpoli** [comment]
dafny-vscode-legacy is much faster. Thanks for the suggestion.

**Comment by camrein** [comment]
Would you mind sharing an example code? Furthermore, since you're explicitly mentioning the verification. How is the responsiveness without the verification?

**Comment by fpoli** [comment]
Regarding an example, take any nontrivial program like https://github.com/dafny-lang/dafny/blob/master/Test/comp/Class.dfy. If I type 10 times `/` then the extension seems to queue 10 verification requests, each of which takes a small time, but overall typing a line of code makes the extension work even for 10-20 seconds.

I'm not sure what "without the verification" means; I'm using the extension just to verify `.dfy` programs. I'm not compiling them.

**Comment by camrein** [comment]
Thanks for the clarification and example. This sounds to me that you have set the automatic verification to "onchange". That's indeed expensive if there are non-trivial programs to verify. That's why I'd suggest switching to "onsave" to mitigate the issue when applying multiple changes in a short timeframe. It seems to me that an option for manual verification would come in handy.

**Comment by fpoli** [comment]
Thanks for the suggestion. If #31 is fixed then "onsave" would be a perfect way for me to manually start the verification. I guess that the proper fix would be that every "onchange" event cancels any past verification request (on the same document). An "Automatic Verification Delay MS" option like the legacy extension might also help mitigating this issue, but I'm not sure how doable this is with the LSP.

**Comment by camrein** [comment]
I'd love to integrate a functionality to cancel any running verification. However, the language server uses the default serialization approach to deal with any incoming document events. Thus, if one takes longer, it blocks all other incoming events. In general, that's fine as these events won't take too long to process. However, for non-trivial programs that take lots of time to verify, that definitely becomes an issue.
Nevertheless, the language server is designed to be multi-threading capable, so I might reconsider some of the things. A neat solution is probably to offload the document verification from event processing to not block this queue. Removing the serialization entirely will probably not be really beneficial since most of the compiler-related things cannot run concurrently.

What I find interesting is the observation you made that you see error messages misaligned as you mentioned in #31. The language server gracefully tracks the document versions and reports them back with the diagnostics. Therefore, it appears to me that VSCode does not respect the document version when displaying these diagnostics.

Last but not least, the delayed verification would surely mitigate the problem further. Currently, the responsibility is entirely in the language server's hands. I have to think a little bit if there's a good way to solve this. But I'd probably have to change one key principle (all or nothing) of it to allow intermediate diagnostics.

**Comment by camrein** [comment]
This should be resolved by https://github.com/dafny-lang/dafny/pull/1456. If there are still performance problems with the new language server, feel free to open another issue.
