### ISSUE TITLE
Show counterexamples ==> trailing spaces are deleted 

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/ide-vscode#27]
VSCode 1.55.2
Dafny extension 1.4.0
macOS 11.2.3

When typing on a .dfy file while "Show counterexamples" is on, a space at the end of a line will be deleted unless a new char is added "soon enough".

**Comment by hmijail** [comment]
This issue is also present in the Dafny extension 1.5.0.

https://user-images.githubusercontent.com/4139546/115805201-d807c600-a427-11eb-84be-9fd3fda56d78.mp4

**Comment by camrein** [comment]
Thanks for your report. Unfortunately, I am unable to reproduce. Neither my Windows nor my Ubuntu machine has such a behavior.
I have quickly scanned through the code if there is something suspicious, but I couldn't identify any location where any editor text is altered.
Although it's strange that this only happens if you have "Show counterexamples" enabled, but you may have some other extensions that interfere with this feature. Have you tried a clean VSCode installation?

**Comment by camrein** [comment]
Since I haven't heard back I assume that this is no longer an issue.

**Comment by hmijail** [comment]
Sorry for taking so long coming back to this.

FWIW, I looked again into this and the deletion is caused by the setting `files.trimTrailingWhitespace`, which takes effect when the file is saved. Since the "Show counterexamples" option seems to cause the file to be saved _almost_ every time that a new character appears, if the new character is a trailing space, then _almost_ always the new space is trimmed.

I guess a good fix would be to not trigger the file saving if the last character is a space.
