### ISSUE TITLE
Not compatible with Visual Studio Code for the Web?

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/ide-vscode#44]
I was very excited to try out the new GitHub Codespaces functionality on the `dafny-lang/dafny` repo, but when I attempt to install this plugin I get the error "The 'Dafny' extension is not available in Visual Studio Code for the Web"

Is this because the plugin attempts to download Dafny? Is there any conceivably way we can work around it?

To reproduce, just navigate to https://github.dev/dafny-lang/dafny and find the Dafny plugin in the marketplace.

**Comment by camrein** [comment]
I've been quickly checking this out. There are some restrictions for web extensions. First and foremost, they must not use any of the Node.JS API: https://code.visualstudio.com/api/extension-guides/web-extensions
Furthermore, they need adaptions to *package.json* to declare themselves as web compatible. For example, instead of the `main` property, they require a `browser` property to denote their entrypoint.

The difficult part will be the language server. I believe without it, the extension only provides syntax highlighting. The language server requires the dotnet runtime and is executed as a separate process. It's not an ultimate showstopper since you can run dotnet applications in the browser using WebAssembly. It's definitely possible since I've already created a web application that runs a Roslyn analyzer from within the browser. However, there are some limitations. For example, threads/tasks are not supported yet. Interestingly enough, there is an API for [WebAssembly language clients](https://code.visualstudio.com/api/extension-guides/web-extensions#language-server-protocol-in-web-extensions). However, the web version will most likely not supported verification since it requires z3.

After concluding my thoughts, I think this sounds like a super interesting field to explore. Although this will not be my primary concern for #41, I'll try to avoid unsupported APIs. Moreover, I have the feeling that we'd need to package the language server with the extension.

**Comment by keyboardDrummer** [comment]
@robin-aws 

The reason that you're getting the error message is that you're using `github.dev`, not code spaces, which runs VS Code without a backing container, so it runs purely in your browser and isn't able to run extensions that have a component that runs outside of the browser, like the Dafny extension. If you follow the [codespaces quickstart quide](https://docs.github.com/en/codespaces/getting-started/quickstart), you can setup a codespace and install the Dafny extension.

I'm not sure how billing works for codespaces, so I don't know how well it fits our use-case. We can also look into GitPod: https://www.gitpod.io/gitpod-vs-github-codespaces

**Comment by keyboardDrummer** [comment]
@camrein 

> The difficult part will be the language server. 

I don't think we should attempt this. It would take much effort and the problem can be fixed by spending a little money on a container.

**Comment by camrein** [comment]
Thanks for your input. I didn't know there were two different web versions of VSCode. I agree with you that it's best to use Codespaces with a backing container.

**Comment by keyboardDrummer** [comment]
Closing since I don't think we want to turn the Dafny IDE extension into a web extension
