### ISSUE TITLE
Code never verifies

### ISSUE THREAD

**Issue by Alexandra-Sparrow0201** [dafny-lang/ide-vscode#58]
Issue Type: <b>Bug</b>

The icon in the corner continuously states it is verifying. I used to be able to compile and run but now it can't even do that anymore. Running one dafny file with a few small equations. Running Windows 11. 

Extension version: 1.8.0
VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.72GB free)|
|Process Argv|--crash-reporter-id 2b4570ea-6fd8-43e6-be0d-57be2dabbdc6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis300:30374797
vsaa593cf:30376535
vssld246cf:30379912

```

</details>

**Comment by camrein** [comment]
Thank you for your bug report and the detailed system information. Your issue sounds somewhat like that the language server crashes.
Since there were some changes and bug fixes since the last official release, would you mind [compiling Dafny from source](https://github.com/dafny-lang/dafny/wiki/INSTALL#windows-source)?
It's sufficient if you install dotnet SDK 5.0 and run the command build command. After compiling, place Z3 (you can grab it from the official Dafny releases) within the binaries directory and set `dafny.languageServerRuntimePath` (settings) to point to *DafnyLanguageServer.dll*.
If you share your Dafny program, I could quickly check if the most recent Dafny sources really fix your issue. If not, I have at least some sources to tackle down the error.

**Comment by MikaelMayer** [comment]
I'm closing this issue as it's likely it was resolved with all the work we did on the language server. At the time you wrote, we had a bug that happened if you typed too quickly.... it's no longer the case. Feel free to post a new issue.
