### ISSUE TITLE
Ensure it never says "verified" when there is a syntax errorv

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/ide-vscode#60]
To reproduce this extension bug:

1) Write some dafny code that verifies. In the toolbar, it says "verified"
2) Insert a typo. In the toolbar, it still says "verified"

I know in the tab "problems" the solution would be there. However, some developers I've personally interacted with actually little use this tab since they usually rely on visual cues like red underline to find issues when the bar says "not verified".
Instead of the problem tab, some are using the terminal to run other scripts like export scripts. This leaves the only place where to look for errors to be the "verified" box, which says verified even if they is a syntax error.

Now, even worse, if the syntax error is in another file.... it still says "verified" for the files that are including this file, even though their code is incorrect.

**Comment by camrein** [comment]
Thanks for reporting. I guess this is related to #32.
The issue should be fixed in the latest but unreleased Dafny language server. If you compile Dafny from the source and make the extension reference the produced *DafnyLanguageServer.dll* binary (`dafny.languageServerRuntimePath` setting), you'll also notice that the status bar messages are now more descriptive.
If that's still not the case, please share some example code. However, judging from the status messages you're describing, I guess your extension is using the automatically installed Dafny v3.2.0.

**Comment by MikaelMayer** [comment]
Yes indeed. Thanks for sharing.
I do compile Dafny from the source code. How do you make the extension reference the produced DafnyLanguageServer.dll library?

**Comment by MikaelMayer** [comment]
A few things I hope I got right.
- Since I'm compiling Dafny using my IDE, the path was in `Binaries/net5.0/` and not `Binaries/`
- I changed both the path to the Dafny.dll and DafnyLanguageServer.dll to point to their most recent compiled versions.
- In windows, I'm writing paths with slashes instead of backslashes.

**Comment by MikaelMayer** [comment]
Excellent! Thanks for these indications. Everything works well with the new version of the Dafny plugin so I'm closing this issue.
