### ISSUE TITLE
Test for range of compatible language server versions in CI

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/ide-vscode#61]
I've been doing something of a post-mortem on the recent Dafny issue where a Dafny user had a really rough time using the newest plugin with existing Dafny code: https://github.com/dafny-lang/dafny/issues/1426.

One of the big takeaways from it so far is that the plugin should make it easier to downgrade to an older version of Dafny, and in fact ensure we know what the minimum compatible version of the server is. 

In my experience, IDEs usually prompt you to configure the programming language SDK/runtime/etc. whenever you create or open a project for the first time, and it usually asks you to download/install them yourself and then configure where they are in the IDE. This makes it a much more explicit decision what version to use, and tends to persist that decision on a per-project rather than IDE-global way. Tweaking the UX in this workflow might also help users realize they should try a different Dafny version when things go awry.

@camrein: I hugely appreciate your jumping on the issues I've been cutting, even the ones that are just half-baked ideas. :) But this one is a lot more urgent in my opinion, in order to do what we can to avoid more users having suboptimal experiences. I'm hesitant to move to the full Dafny 3.3.0 release until we have some good mutual mechanisms in place, to make sure it's easy for users to keep getting plugin releases with all the great improvements you keep making, but to also make sure they can safely stay on the Dafny version currently working for them.

**Comment by camrein** [comment]
> I've been doing something of a post-mortem on the recent Dafny issue where a Dafny user had a really rough time using the newest plugin with existing Dafny code: [dafny-lang/dafny#1426](https://github.com/dafny-lang/dafny/issues/1426).

This issue was indeed unpleasant. This may drive again the necessity to be able to release language server updates more independently from Dafny releases, or increase the release cycle. Most of the issues we received were not related to the extension but the language server. Alternatively, we might consider something like a nightly build to not have users compile Dafny manually in such urgent cases (or have us provide the binaries like in the issue above).

> One of the big takeaways from it so far is that the plugin should make it easier to downgrade to an older version of Dafny, and in fact ensure we know what the minimum compatible version of the server is.

Just to make sure we're talking about the same. This extension is only compatible to Dafny 3 onwards since it requires the LSP language server. The previous extension for Dafny 2 relied on DafnyServer which works differently. So it's not possible to downgrade prior Dafny 3 with this extension.
When refurbishing the code base of this extension, I also revised the mechanism of the version check and automatic upgrade. Users are free to configure a custom installation just as before (`dafny.languageServerRuntimePath` setting). However, I think the currently released extension version has problems when having configured a Dafny version lower than the one that was targeted with its release (v3.2.0 in this case).
This behavior has changed with the current codebase. There will only be a notification that the configured Dafny version is outdated and only attempt to update automatic installations. As I know that you're using (or at least experimenting) with compiling the extension from source, you might give it a try to see if it now behaves according to your expectations.

I'd happily publish a new version. But the most of the recent features are provided by the language server, so an update is not so reasonable out of user perspective. The most notable change is that the extension now displays the installation progress. But if you can confirm that the extension behaves the way you expect, I can release the update now. Unless you have some concrete input on how I should handle "fresh installations" besides the currently available options. But I have to note that the current procedure is similar (if not the same) as the one of VSCode's C# extension (install the necessary files upon first use but provide an option to override the language server).

PS: With each push to this repository, a fully packaged version of this extension is available within the executed action. See for example the [latest push to master](https://github.com/dafny-lang/ide-vscode/actions/runs/1331902262). In case you do not want to package the extension yourself to redistribute unreleased versions.

**Comment by keyboardDrummer** [comment]
I think in the future, a Dafny project will have to specify in a configuration file what version of Dafny it's using, and the IDE should pick that up, ensure the corresponding Dafny version is installed, and use its language server.

The IDE should also try to remain compatible with older Dafny language servers. If the language server API changes, the IDE should try to support both the new and old API version. If a Dafny project is opened that uses a Dafny version older than what the IDE supports, the user should be notified.

One question is whether we should let the Dafny IDE work with Dafny versions that are newer than the IDE. I think the simplest option is not to allow that, but this means we need to release a new IDE version every time we release a new Dafny version, even if there are no IDE feature changes. Currently this is the case since we need to update [the downloaded Dafny version](https://github.com/dafny-lang/ide-vscode/blob/master/src/constants.ts#L43) to let the IDE use a newer Dafny.

If we do allow the IDE to work with a newer Dafny version, there's the risk that a Dafny version is published with an API that the latest IDE doesn't support. We could protect against this by letting Dafny vend an API version number, and letting the IDE know what the latest API version is that it supports. **We would augment the Dafny release process with a check that verifies the latest published IDE supports the about-to-published Dafny API version.**

We would also augment the IDE, so that if for some reason the Dafny API version is too new for the IDE, for example if the user is using an outdated IDE because they turned off automatic updates, the IDE would notify the user who can then decide to do one of these:
- Install the latest Dafny IDE
- Use an older Dafny version with the older IDE
- Use the newer Dafny version without the IDE

-----

Right now, since Dafny projects don't specify which Dafny version they want to use, I think the current behavior of using the latest Dafny version that the IDE is aware of, is fine. If we don't want to publish a new IDE version for every new Dafny version, we can let the IDE use the latest published Dafny version, but in that case I think we also need to add the two safety mechanisms I described above.

**Comment by MikaelMayer** [comment]
We currently can test multiple versions of Dafny easily, so I'm closing this issue.
