### ISSUE TITLE
Developer: Reload Window spawns additional dotnet processes but does not clean up old one

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#76]
On OSX, every time I reload the IDE, I get an additional language server.
But the old language server process is left around.

**Comment by camrein** [comment]
Thank you for reporting this bug. I have revised the whole extension and I believe this shouldn't be an issue anymore with the next release (v2.0.0):
https://github.com/dafny-lang/ide-vscode/blob/f6f3fc34fef4d0829fea908aa882adefdcf5438f/src/extension.ts#L24-L26
This deactivation procedure was missing before. Am I right when I assume that you're using the latest version released on the Marketplace (v1.8.0)? What I find interesting is that I couldn't reproduce it on Windows with this version. I May have to give it a try on OSX later to ensure that it's really fixed.

**Comment by seebees** [comment]
I have 6 `dotnet` processes running.
If I `killall dotnet` and then reload, I will have 2.
It _may_ be that there is a limit? I'm not sure.

**Comment by camrein** [comment]
I've now tested it on my mac and I can confirm the issue. I've identified one possible issue with the following line:
https://github.com/dafny-lang/ide-vscode/blob/f6f3fc34fef4d0829fea908aa882adefdcf5438f/src/extension.ts#L59
The result of the `start` command should be added to the context subscriptions. However, it did not resolve that old instances are not cleaned up as they should.
What I find interesting is that it appears that VSCode does not wait for the `client.stop()` command to complete (at least the debugger gets detached before its completion).

**Comment by seebees** [comment]
Nice!
I found this because I suspect that verification is hanging.
I have had verification take longer than expected and so I reload and the restart verification and it completes quite quickly.

I don't have a lot of details on why the verification seems to hang.
Though I suspect that it has something to do with starting verification and then restarting verification with a syntax error.(?) not sure.

**Comment by camrein** [comment]
Usually, if the verification is hanging, you might see a *z3* process running. If you kill this one (with the latest release, there might be more due to better utilization of the available cores), the verification should finish immediately.
Moreover, the language server aims to cancel active verifications if a change is received. Unfortunately, it appears that it's not always possible, as observed in https://github.com/dafny-lang/dafny/issues/1489.

But from my tests, it does not appear to relate to the verification. Although I didn't disable it, I could reproduce the error with simple code that verify in a few milliseconds. But I'll give it a try with disabled verification just to be on the safe side.

**Comment by seebees** [comment]
I have not seen this in awhile,
I think we can close it.
