### ISSUE TITLE
String highlighting in the IDE only

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#85]
The following in VSCode looks strange, however here in GitHub, it looks fine...
```dafny
method Foo() returns (res: Result<string, string>)
  {
    :- Need(true, "Not a string, the parens are doing it ().");
    :- Need(!false, "The code is higlites as a string and this string is code");
    :- Need(false == false, "???");
  }
```

**Comment by camrein** [comment]
Thanks a lot for your report. The strings are indeed rendered strangely:
![image](https://user-images.githubusercontent.com/18049310/142372692-d4cebb5b-3624-4dbd-8b3c-523f2d108ee7.png)

I will check how to improve upon this. One thing I'll change is that strings are no longer highlighted over multiple lines since Dafny does not support multiline strings with `"`. This will avoid breaking the syntax highlighting for the whole file in case there's another issue.
