### ISSUE TITLE
Counter examples should wrap

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#88]
Counter examples are WAY too long.
And interacting with them is difficult.
Every `=` should be in its own line.
As well as every `@n`.

Instead of

```
foo:Other.Thing.Foo = SOME_LONG_CONSTANT_NAME bar:More.Long.Type.Name = Name(with := @0, lots := @1, and := @2) @0:Lots.Of.Information @1:That.Is.Very @2:Hard.To.Read
```

I suggest
```
foo:Other.Thing.Foo = SOME_LONG_CONSTANT_NAME
bar:More.Long.Type.Name = Name(with := @0, lots := @1, and := @2)
@0:Lots.Of.Information
@1:That.Is.Very
@2:Hard.To.Read
```
Alternatively (or in addition), a way to send this information to the clipboard :)

**Comment by camrein** [comment]
I've seen this problem too. That's why I've started experimenting with an alternative approach in #52. At this time, I didn't continue working on it because I was envisioning better support for reference types. Nevertheless, I could integrate the current version as I believe it's more practical than the inline view. Or do you think your clipboard approach would be more useful in your case?

Moreover, you've started a great discussion in #75 for a big picture on how to deal with verification and counterexamples. However, this is probably some long-term work.

**Comment by seebees** [comment]
I think that having it be more readable will always be better.
In combination with the language server, having been given a counter example, I would love to be able to "pin" parts of it.

So if it is nicely flattened so I can read it,
then maybe I could also interact with it.
And ask, well, if I pin `@0 == 5` for example, can Dafny still find a counter example?

**Comment by codyroux** [comment]
+ 1 on line breaks, and it would be pretty nice if one could select the text, say, to copy it.

I had other opinions which I summarized here: https://github.com/dafny-lang/dafny/issues/2280

**Comment by MikaelMayer** [comment]
I'm closing this issue, as it's now possible to copy in the clipboard the counter-examples.
Although it's not pretty, it's always better than the statu quo .We can't wrap counter-examples because that would be too disrupting on the user experience; however, we can - and we have some plans for that - to make a counter example visualization. @dijkstracula  was thinking of that.
