### ISSUE TITLE
Compile and Run on an unsaved editor closes it and does not run

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/ide-vscode#89]
![ide-vscode-new-issue](https://user-images.githubusercontent.com/3601079/143303592-867d466d-50cc-4459-a1ca-881669954c15.gif)

Steps to reproduce this problem

- File > new file
- Select a language (Dafny)
- Paste some code like this:
```
method Main() {
  print "ok";
}
```
- Right-click, compile and run (or press F5)
- Give any name on any path, press save.

**Problem#1**: It displays this in the embedded terminal
```
PS C:\Users\.....> & "C:\Program Files\dotnet\dotnet.EXE" "c:\Users\.....\.vscode\extensions\correctnesslab.dafny-vscode-2.0.2\out\resources\dafny\Dafny.dll" "Untitled-1" /verifyAllModules /spillTargetCode:1 /compile:3 /out:bin\Untitled-1
*** Error: 'Untitled-1': Filename extension '' is not supported. Input files must be Dafny programs (.dfy) or C# files (.cs) or managed DLLS (.dll)
```
which is using `Untitled-1` instead of the newly entered file name.

**Problem#2**: It closes the tab containing the code, and offers no way to reopen it.

The file is correctly saved though.

**Comment by camrein** [comment]
Thanks a lot for this bug report. That's an interesting finding that is related to the following VSCode bug: https://github.com/microsoft/vscode/issues/29156
Since it appears that it won't be fixed in the near future, we have to create a workaround ourselves. For example, force the users to manually save the untitled document before compiling.
